import Sidebar from '@/components/Sidebar';
import './globals.css';
import { Inter } from 'next/font/google';
import SupabaseProvider from '@/providers/SupabaseProviders';
import { Metadata } from 'next';
import UserProvider from '@/providers/UserProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Spotify Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProvider>
          <UserProvider>
            <Sidebar>{children}</Sidebar>
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
